; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 11220621-x86_64 macOS                   
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppDistEst                                = true                                    
ppPairTaxa                               = true                                    
[ AnalysisSettings ]
Analysis                                 = Distance Estimation                     
Scope                                    = Pairs of taxa                           
Estimate Variance                        = ====================                    
Variance Estimation Method               = None                                    
No. of Bootstrap Replications            = Not Applicable                          
Substitution Model                       = ====================                    
Substitutions Type                       = Syn-Nonsynonymous                       
Model/Method                             = Modified Nei-Gojobori method (Proportion)
Fixed Transition/Transversion Ratio      = 2.00                                    
Substitutions to Include                 = n: Nonsynonymous only                   
Rates and Patterns                       = ====================                    
Rates among Sites                        = Uniform Rates                           
Gamma Parameter                          = Not Applicable                          
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Complete deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
Genetic Code Table                       = Standard                                
Genetic Code                             = FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
